const types = {
  GET_ALL_CATEGORIES_START: "@products/GET_ALL_CATEGORIES_START",
  GET_ALL_CATEGORIES_SUCCESS: "@products/GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "@products/GET_ALL_CATEGORIES_FAILURE",
};

export default types;
